const Actions = {

    SEARCH_FETCHED: 'SEARCH_FETCHED',

    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    
    SINGLE_DATA_FETCHED: 'SINGLE_DATA',
    
    COMPLETE_DATA_FETCHED: 'COMPLETE_DATA_FETCHED',
    LOADING_COMPLETE_DATA: 'LOADING_COMPLETE_DATA'
}

export default Actions;